services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1 # バッファリングを無効にする（リアルタイムでログ確認できる）
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fastapiuser
      POSTGRES_PASSWORD: fastapipass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: fleamarket
    hostname: postgres
    user: root
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: fastapi@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always
